"""Prove explicit design-local duplicates without certifying external uniqueness."""
from ..registry import resource_check
from ..common.context_values import _Context, linked, value
from ..common.literals import known_scope, literal


def token(ctx,resource,spec):
    parts=[]
    for key in spec['paths']:
        path='/properties/'+key;raw=value(ctx,resource,path)
        if spec['mode']=='integer':
            if type(raw) is not int:return None
        elif spec['mode']=='ordered_array':
            if not isinstance(raw,list):return None
            raw=tuple(value(ctx,resource,path+'/'+str(i)) for i in range(len(raw)))
            if not all(literal(x) for x in raw):return None
        else:
            if not literal(raw):return None
            if spec['mode']=='ascii_lower':
                if not raw.isascii():return None
                raw=raw.lower()
        parts.append(raw)
    return tuple(parts)


def owner(ctx,resource,spec):
    if not known_scope(resource):return None
    if resource.template is not None and resource.template.state.value!='KNOWN':return None
    if spec['parent']:
        key,kind=spec['parent'];target=linked(ctx,resource,'/properties/'+key,kind)
        return target.id if target else None
    return ('scope',resource.scope.environment,resource.scope.account,resource.scope.region)


SPECS = {'AWS::AppRunner::Service': {'paths': ['ServiceName'],
                             'parent': None,
                             'mode': 'string',
                             'type': 'AWS::AppRunner::Service',
                             'question_index': 4,
                             'candidate_index': 2,
                             'rule_id': 'APPRUNNER_SERVICE_DESIGN_DUPLICATE',
                             'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-apprunner-service.html',
                                             'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Athena::DataCatalog': {'paths': ['Name'],
                              'parent': None,
                              'mode': 'string',
                              'type': 'AWS::Athena::DataCatalog',
                              'question_index': 2,
                              'candidate_index': 3,
                              'rule_id': 'ATHENA_DATACATALOG_DESIGN_DUPLICATE',
                              'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-athena-datacatalog.html',
                                              'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Bedrock::IntelligentPromptRouter': {'paths': ['PromptRouterName'],
                                           'parent': None,
                                           'mode': 'string',
                                           'type': 'AWS::Bedrock::IntelligentPromptRouter',
                                           'question_index': 0,
                                           'candidate_index': 4,
                                           'rule_id': 'BEDROCK_INTELLIGENTPROMPTROUTER_DESIGN_DUPLICATE',
                                           'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrock-intelligentpromptrouter.html',
                                                           'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::BrowserCustom': {'paths': ['Name'],
                                          'parent': None,
                                          'mode': 'string',
                                          'type': 'AWS::BedrockAgentCore::BrowserCustom',
                                          'question_index': 0,
                                          'candidate_index': 5,
                                          'rule_id': 'BEDROCKAGENTCORE_BROWSERCUSTOM_DESIGN_DUPLICATE',
                                          'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-browsercustom.html',
                                                          'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::ConfigurationBundle': {'paths': ['BundleName'],
                                                'parent': None,
                                                'mode': 'string',
                                                'type': 'AWS::BedrockAgentCore::ConfigurationBundle',
                                                'question_index': 0,
                                                'candidate_index': 6,
                                                'rule_id': 'BEDROCKAGENTCORE_CONFIGURATIONBUNDLE_DESIGN_DUPLICATE',
                                                'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-configurationbundle.html',
                                                                'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::Dataset': {'paths': ['DatasetName'],
                                    'parent': None,
                                    'mode': 'ascii_lower',
                                    'type': 'AWS::BedrockAgentCore::Dataset',
                                    'question_index': 0,
                                    'candidate_index': 7,
                                    'rule_id': 'BEDROCKAGENTCORE_DATASET_DESIGN_DUPLICATE',
                                    'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-dataset.html',
                                                    'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::Evaluator': {'paths': ['EvaluatorName'],
                                      'parent': None,
                                      'mode': 'string',
                                      'type': 'AWS::BedrockAgentCore::Evaluator',
                                      'question_index': 0,
                                      'candidate_index': 8,
                                      'rule_id': 'BEDROCKAGENTCORE_EVALUATOR_DESIGN_DUPLICATE',
                                      'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-evaluator.html',
                                                      'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::OAuth2CredentialProvider': {'paths': ['Name'],
                                                     'parent': None,
                                                     'mode': 'string',
                                                     'type': 'AWS::BedrockAgentCore::OAuth2CredentialProvider',
                                                     'question_index': 0,
                                                     'candidate_index': 10,
                                                     'rule_id': 'BEDROCKAGENTCORE_OAUTH2CREDENTIALPROVIDER_DESIGN_DUPLICATE',
                                                     'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-oauth2credentialprovider.html',
                                                                     'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::OnlineEvaluationConfig': {'paths': ['OnlineEvaluationConfigName'],
                                                   'parent': None,
                                                   'mode': 'string',
                                                   'type': 'AWS::BedrockAgentCore::OnlineEvaluationConfig',
                                                   'question_index': 0,
                                                   'candidate_index': 11,
                                                   'rule_id': 'BEDROCKAGENTCORE_ONLINEEVALUATIONCONFIG_DESIGN_DUPLICATE',
                                                   'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-onlineevaluationconfig.html',
                                                                   'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::PolicyEngine': {'paths': ['Name'],
                                         'parent': None,
                                         'mode': 'string',
                                         'type': 'AWS::BedrockAgentCore::PolicyEngine',
                                         'question_index': 0,
                                         'candidate_index': 13,
                                         'rule_id': 'BEDROCKAGENTCORE_POLICYENGINE_DESIGN_DUPLICATE',
                                         'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-policyengine.html',
                                                         'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::WorkloadIdentity': {'paths': ['Name'],
                                             'parent': None,
                                             'mode': 'string',
                                             'type': 'AWS::BedrockAgentCore::WorkloadIdentity',
                                             'question_index': 0,
                                             'candidate_index': 14,
                                             'rule_id': 'BEDROCKAGENTCORE_WORKLOADIDENTITY_DESIGN_DUPLICATE',
                                             'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-workloadidentity.html',
                                                             'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockMantle::Project': {'paths': ['Name'],
                                 'parent': None,
                                 'mode': 'string',
                                 'type': 'AWS::BedrockMantle::Project',
                                 'question_index': 0,
                                 'candidate_index': 15,
                                 'rule_id': 'BEDROCKMANTLE_PROJECT_DESIGN_DUPLICATE',
                                 'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockmantle-project.html',
                                                 'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Cases::Domain': {'paths': ['Name'],
                        'parent': None,
                        'mode': 'string',
                        'type': 'AWS::Cases::Domain',
                        'question_index': 0,
                        'candidate_index': 16,
                        'rule_id': 'CASES_DOMAIN_DESIGN_DUPLICATE',
                        'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cases-domain.html',
                                        'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CloudFormation::GuardHook': {'paths': ['Alias'],
                                    'parent': None,
                                    'mode': 'string',
                                    'type': 'AWS::CloudFormation::GuardHook',
                                    'question_index': 2,
                                    'candidate_index': 18,
                                    'rule_id': 'CLOUDFORMATION_GUARDHOOK_DESIGN_DUPLICATE',
                                    'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudformation-guardhook.html',
                                                    'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CloudFormation::LambdaHook': {'paths': ['Alias'],
                                     'parent': None,
                                     'mode': 'string',
                                     'type': 'AWS::CloudFormation::LambdaHook',
                                     'question_index': 0,
                                     'candidate_index': 19,
                                     'rule_id': 'CLOUDFORMATION_LAMBDAHOOK_DESIGN_DUPLICATE',
                                     'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudformation-lambdahook.html',
                                                     'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CloudFormation::Macro': {'paths': ['Name'],
                                'parent': None,
                                'mode': 'string',
                                'type': 'AWS::CloudFormation::Macro',
                                'question_index': 0,
                                'candidate_index': 20,
                                'rule_id': 'CLOUDFORMATION_MACRO_DESIGN_DUPLICATE',
                                'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudformation-macro.html',
                                                'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CloudFormation::StackSet': {'paths': ['StackSetName'],
                                   'parent': None,
                                   'mode': 'string',
                                   'type': 'AWS::CloudFormation::StackSet',
                                   'question_index': 6,
                                   'candidate_index': 21,
                                   'rule_id': 'CLOUDFORMATION_STACKSET_DESIGN_DUPLICATE',
                                   'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudformation-stackset.html',
                                                   'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CloudFormation::TypeActivation': {'paths': ['TypeNameAlias'],
                                         'parent': None,
                                         'mode': 'string',
                                         'type': 'AWS::CloudFormation::TypeActivation',
                                         'question_index': 0,
                                         'candidate_index': 22,
                                         'rule_id': 'CLOUDFORMATION_TYPEACTIVATION_DESIGN_DUPLICATE',
                                         'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudformation-typeactivation.html',
                                                         'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CloudTrail::Channel': {'paths': ['Source'],
                              'parent': None,
                              'mode': 'string',
                              'type': 'AWS::CloudTrail::Channel',
                              'question_index': 0,
                              'candidate_index': 23,
                              'rule_id': 'CLOUDTRAIL_CHANNEL_DESIGN_DUPLICATE',
                              'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudtrail-channel.html',
                                              'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CodeBuild::Project': {'paths': ['Name'],
                             'parent': None,
                             'mode': 'string',
                             'type': 'AWS::CodeBuild::Project',
                             'question_index': 0,
                             'candidate_index': 24,
                             'rule_id': 'CODEBUILD_PROJECT_DESIGN_DUPLICATE',
                             'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-codebuild-project.html',
                                             'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CodeCommit::Repository': {'paths': ['RepositoryName'],
                                 'parent': None,
                                 'mode': 'string',
                                 'type': 'AWS::CodeCommit::Repository',
                                 'question_index': 0,
                                 'candidate_index': 25,
                                 'rule_id': 'CODECOMMIT_REPOSITORY_DESIGN_DUPLICATE',
                                 'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-codecommit-repository.html',
                                                 'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CodeConnections::Connection': {'paths': ['ConnectionName'],
                                      'parent': None,
                                      'mode': 'string',
                                      'type': 'AWS::CodeConnections::Connection',
                                      'question_index': 0,
                                      'candidate_index': 26,
                                      'rule_id': 'CODECONNECTIONS_CONNECTION_DESIGN_DUPLICATE',
                                      'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-codeconnections-connection.html',
                                                      'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CodeStarConnections::Connection': {'paths': ['ConnectionName'],
                                          'parent': None,
                                          'mode': 'string',
                                          'type': 'AWS::CodeStarConnections::Connection',
                                          'question_index': 0,
                                          'candidate_index': 27,
                                          'rule_id': 'CODESTARCONNECTIONS_CONNECTION_DESIGN_DUPLICATE',
                                          'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-codestarconnections-connection.html',
                                                          'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::CodeStarNotifications::NotificationRule': {'paths': ['Name'],
                                                  'parent': None,
                                                  'mode': 'string',
                                                  'type': 'AWS::CodeStarNotifications::NotificationRule',
                                                  'question_index': 1,
                                                  'candidate_index': 28,
                                                  'rule_id': 'CODESTARNOTIFICATIONS_NOTIFICATIONRULE_DESIGN_DUPLICATE',
                                                  'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-codestarnotifications-notificationrule.html',
                                                                  'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Glue::CustomEntityType': {'paths': ['Name'],
                                 'parent': None,
                                 'mode': 'string',
                                 'type': 'AWS::Glue::CustomEntityType',
                                 'question_index': 0,
                                 'candidate_index': 36,
                                 'rule_id': 'GLUE_CUSTOMENTITYTYPE_DESIGN_DUPLICATE',
                                 'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-glue-customentitytype.html',
                                                 'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Glue::MLTransform': {'paths': ['Name'],
                            'parent': None,
                            'mode': 'string',
                            'type': 'AWS::Glue::MLTransform',
                            'question_index': 2,
                            'candidate_index': 37,
                            'rule_id': 'GLUE_MLTRANSFORM_DESIGN_DUPLICATE',
                            'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-glue-mltransform.html',
                                            'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::GuardDuty::IPSet': {'paths': ['Name'],
                           'parent': None,
                           'mode': 'string',
                           'type': 'AWS::GuardDuty::IPSet',
                           'question_index': 0,
                           'candidate_index': 40,
                           'rule_id': 'GUARDDUTY_IPSET_DESIGN_DUPLICATE',
                           'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-guardduty-ipset.html',
                                           'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::GuardDuty::ThreatIntelSet': {'paths': ['Name'],
                                    'parent': None,
                                    'mode': 'string',
                                    'type': 'AWS::GuardDuty::ThreatIntelSet',
                                    'question_index': 0,
                                    'candidate_index': 41,
                                    'rule_id': 'GUARDDUTY_THREATINTELSET_DESIGN_DUPLICATE',
                                    'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-guardduty-threatintelset.html',
                                                    'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ImageBuilder::InfrastructureConfiguration': {'paths': ['Name'],
                                                    'parent': None,
                                                    'mode': 'string',
                                                    'type': 'AWS::ImageBuilder::InfrastructureConfiguration',
                                                    'question_index': 2,
                                                    'candidate_index': 43,
                                                    'rule_id': 'IMAGEBUILDER_INFRASTRUCTURECONFIGURATION_DESIGN_DUPLICATE',
                                                    'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-imagebuilder-infrastructureconfiguration.html',
                                                                    'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ImageBuilder::LifecyclePolicy': {'paths': ['Name'],
                                        'parent': None,
                                        'mode': 'string',
                                        'type': 'AWS::ImageBuilder::LifecyclePolicy',
                                        'question_index': 2,
                                        'candidate_index': 44,
                                        'rule_id': 'IMAGEBUILDER_LIFECYCLEPOLICY_DESIGN_DUPLICATE',
                                        'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-imagebuilder-lifecyclepolicy.html',
                                                        'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Inspector::AssessmentTarget': {'paths': ['AssessmentTargetName'],
                                      'parent': None,
                                      'mode': 'string',
                                      'type': 'AWS::Inspector::AssessmentTarget',
                                      'question_index': 0,
                                      'candidate_index': 45,
                                      'rule_id': 'INSPECTOR_ASSESSMENTTARGET_DESIGN_DUPLICATE',
                                      'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-inspector-assessmenttarget.html',
                                                      'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Invoicing::InvoiceUnit': {'paths': ['Name'],
                                 'parent': None,
                                 'mode': 'string',
                                 'type': 'AWS::Invoicing::InvoiceUnit',
                                 'question_index': 0,
                                 'candidate_index': 47,
                                 'rule_id': 'INVOICING_INVOICEUNIT_DESIGN_DUPLICATE',
                                 'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-invoicing-invoiceunit.html',
                                                 'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::IoT::DomainConfiguration': {'paths': ['DomainConfigurationName'],
                                   'parent': None,
                                   'mode': 'string',
                                   'type': 'AWS::IoT::DomainConfiguration',
                                   'question_index': 2,
                                   'candidate_index': 48,
                                   'rule_id': 'IOT_DOMAINCONFIGURATION_DESIGN_DUPLICATE',
                                   'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-iot-domainconfiguration.html',
                                                   'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::KafkaConnect::Connector': {'paths': ['ConnectorName'],
                                  'parent': None,
                                  'mode': 'string',
                                  'type': 'AWS::KafkaConnect::Connector',
                                  'question_index': 0,
                                  'candidate_index': 49,
                                  'rule_id': 'KAFKACONNECT_CONNECTOR_DESIGN_DUPLICATE',
                                  'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-kafkaconnect-connector.html',
                                                  'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Kinesis::Channel': {'paths': ['ChannelName'],
                           'parent': None,
                           'mode': 'string',
                           'type': 'AWS::Kinesis::Channel',
                           'question_index': 2,
                           'candidate_index': 50,
                           'rule_id': 'KINESIS_CHANNEL_DESIGN_DUPLICATE',
                           'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-kinesis-channel.html',
                                           'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::KinesisVideo::SignalingChannel': {'paths': ['Name'],
                                         'parent': None,
                                         'mode': 'string',
                                         'type': 'AWS::KinesisVideo::SignalingChannel',
                                         'question_index': 0,
                                         'candidate_index': 51,
                                         'rule_id': 'KINESISVIDEO_SIGNALINGCHANNEL_DESIGN_DUPLICATE',
                                         'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-kinesisvideo-signalingchannel.html',
                                                         'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaLive::CloudWatchAlarmTemplate': {'paths': ['Name'],
                                             'parent': None,
                                             'mode': 'string',
                                             'type': 'AWS::MediaLive::CloudWatchAlarmTemplate',
                                             'question_index': 1,
                                             'candidate_index': 61,
                                             'rule_id': 'MEDIALIVE_CLOUDWATCHALARMTEMPLATE_DESIGN_DUPLICATE',
                                             'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-medialive-cloudwatchalarmtemplate.html',
                                                             'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaLive::CloudWatchAlarmTemplateGroup': {'paths': ['Name'],
                                                  'parent': None,
                                                  'mode': 'string',
                                                  'type': 'AWS::MediaLive::CloudWatchAlarmTemplateGroup',
                                                  'question_index': 0,
                                                  'candidate_index': 62,
                                                  'rule_id': 'MEDIALIVE_CLOUDWATCHALARMTEMPLATEGROUP_DESIGN_DUPLICATE',
                                                  'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-medialive-cloudwatchalarmtemplategroup.html',
                                                                  'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaLive::EventBridgeRuleTemplate': {'paths': ['Name'],
                                             'parent': None,
                                             'mode': 'string',
                                             'type': 'AWS::MediaLive::EventBridgeRuleTemplate',
                                             'question_index': 0,
                                             'candidate_index': 63,
                                             'rule_id': 'MEDIALIVE_EVENTBRIDGERULETEMPLATE_DESIGN_DUPLICATE',
                                             'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-medialive-eventbridgeruletemplate.html',
                                                             'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaLive::EventBridgeRuleTemplateGroup': {'paths': ['Name'],
                                                  'parent': None,
                                                  'mode': 'string',
                                                  'type': 'AWS::MediaLive::EventBridgeRuleTemplateGroup',
                                                  'question_index': 0,
                                                  'candidate_index': 64,
                                                  'rule_id': 'MEDIALIVE_EVENTBRIDGERULETEMPLATEGROUP_DESIGN_DUPLICATE',
                                                  'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-medialive-eventbridgeruletemplategroup.html',
                                                                  'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaLive::SignalMap': {'paths': ['Name'],
                               'parent': None,
                               'mode': 'string',
                               'type': 'AWS::MediaLive::SignalMap',
                               'question_index': 0,
                               'candidate_index': 66,
                               'rule_id': 'MEDIALIVE_SIGNALMAP_DESIGN_DUPLICATE',
                               'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-medialive-signalmap.html',
                                               'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ObservabilityAdmin::TelemetryPipelines': {'paths': ['Name'],
                                                 'parent': None,
                                                 'mode': 'string',
                                                 'type': 'AWS::ObservabilityAdmin::TelemetryPipelines',
                                                 'question_index': 1,
                                                 'candidate_index': 67,
                                                 'rule_id': 'OBSERVABILITYADMIN_TELEMETRYPIPELINES_DESIGN_DUPLICATE',
                                                 'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-observabilityadmin-telemetrypipelines.html',
                                                                 'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::OpenSearchServerless::Collection': {'paths': ['Name'],
                                           'parent': None,
                                           'mode': 'string',
                                           'type': 'AWS::OpenSearchServerless::Collection',
                                           'question_index': 2,
                                           'candidate_index': 68,
                                           'rule_id': 'OPENSEARCHSERVERLESS_COLLECTION_DESIGN_DUPLICATE',
                                           'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-opensearchserverless-collection.html',
                                                           'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::RAM::Permission': {'paths': ['Name'],
                          'parent': None,
                          'mode': 'string',
                          'type': 'AWS::RAM::Permission',
                          'question_index': 2,
                          'candidate_index': 69,
                          'rule_id': 'RAM_PERMISSION_DESIGN_DUPLICATE',
                          'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-ram-permission.html',
                                          'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Redshift::ScheduledAction': {'paths': ['ScheduledActionName'],
                                    'parent': None,
                                    'mode': 'string',
                                    'type': 'AWS::Redshift::ScheduledAction',
                                    'question_index': 2,
                                    'candidate_index': 70,
                                    'rule_id': 'REDSHIFT_SCHEDULEDACTION_DESIGN_DUPLICATE',
                                    'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-redshift-scheduledaction.html',
                                                    'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ResourceGroups::Group': {'paths': ['Name'],
                                'parent': None,
                                'mode': 'string',
                                'type': 'AWS::ResourceGroups::Group',
                                'question_index': 0,
                                'candidate_index': 71,
                                'rule_id': 'RESOURCEGROUPS_GROUP_DESIGN_DUPLICATE',
                                'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-resourcegroups-group.html',
                                                'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::S3Express::DirectoryBucket': {'paths': ['BucketName'],
                                     'parent': None,
                                     'mode': 'string',
                                     'type': 'AWS::S3Express::DirectoryBucket',
                                     'question_index': 1,
                                     'candidate_index': 73,
                                     'rule_id': 'S3EXPRESS_DIRECTORYBUCKET_DESIGN_DUPLICATE',
                                     'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3express-directorybucket.html',
                                                     'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::S3Vectors::VectorBucket': {'paths': ['VectorBucketName'],
                                  'parent': None,
                                  'mode': 'string',
                                  'type': 'AWS::S3Vectors::VectorBucket',
                                  'question_index': 1,
                                  'candidate_index': 74,
                                  'rule_id': 'S3VECTORS_VECTORBUCKET_DESIGN_DUPLICATE',
                                  'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3vectors-vectorbucket.html',
                                                  'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::SageMaker::PartnerApp': {'paths': ['Name'],
                                'parent': None,
                                'mode': 'string',
                                'type': 'AWS::SageMaker::PartnerApp',
                                'question_index': 0,
                                'candidate_index': 77,
                                'rule_id': 'SAGEMAKER_PARTNERAPP_DESIGN_DUPLICATE',
                                'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-sagemaker-partnerapp.html',
                                                'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::SageMaker::ProcessingJob': {'paths': ['ProcessingJobName'],
                                   'parent': None,
                                   'mode': 'string',
                                   'type': 'AWS::SageMaker::ProcessingJob',
                                   'question_index': 1,
                                   'candidate_index': 78,
                                   'rule_id': 'SAGEMAKER_PROCESSINGJOB_DESIGN_DUPLICATE',
                                   'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-sagemaker-processingjob.html',
                                                   'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::SageMaker::TrialComponent': {'paths': ['TrialComponentName'],
                                    'parent': None,
                                    'mode': 'ascii_lower',
                                    'type': 'AWS::SageMaker::TrialComponent',
                                    'question_index': 1,
                                    'candidate_index': 80,
                                    'rule_id': 'SAGEMAKER_TRIALCOMPONENT_DESIGN_DUPLICATE',
                                    'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-sagemaker-trialcomponent.html',
                                                    'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ServiceCatalog::CloudFormationProvisionedProduct': {'paths': ['ProvisionedProductName'],
                                                           'parent': None,
                                                           'mode': 'string',
                                                           'type': 'AWS::ServiceCatalog::CloudFormationProvisionedProduct',
                                                           'question_index': 2,
                                                           'candidate_index': 84,
                                                           'rule_id': 'SERVICECATALOG_CLOUDFORMATIONPROVISIONEDPRODUCT_DESIGN_DUPLICATE',
                                                           'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-servicecatalog-cloudformationprovisionedproduct.html',
                                                                           'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ServiceCatalogAppRegistry::Application': {'paths': ['Name'],
                                                 'parent': None,
                                                 'mode': 'string',
                                                 'type': 'AWS::ServiceCatalogAppRegistry::Application',
                                                 'question_index': 0,
                                                 'candidate_index': 85,
                                                 'rule_id': 'SERVICECATALOGAPPREGISTRY_APPLICATION_DESIGN_DUPLICATE',
                                                 'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-servicecatalogappregistry-application.html',
                                                                 'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::SupportAuthZ::SupportPermit': {'paths': ['Name'],
                                      'parent': None,
                                      'mode': 'string',
                                      'type': 'AWS::SupportAuthZ::SupportPermit',
                                      'question_index': 1,
                                      'candidate_index': 87,
                                      'rule_id': 'SUPPORTAUTHZ_SUPPORTPERMIT_DESIGN_DUPLICATE',
                                      'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-supportauthz-supportpermit.html',
                                                      'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Synthetics::Group': {'paths': ['Name'],
                            'parent': None,
                            'mode': 'string',
                            'type': 'AWS::Synthetics::Group',
                            'question_index': 0,
                            'candidate_index': 88,
                            'rule_id': 'SYNTHETICS_GROUP_DESIGN_DUPLICATE',
                            'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-synthetics-group.html',
                                            'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Timestream::InfluxDBCluster': {'paths': ['Name'],
                                      'parent': None,
                                      'mode': 'string',
                                      'type': 'AWS::Timestream::InfluxDBCluster',
                                      'question_index': 1,
                                      'candidate_index': 89,
                                      'rule_id': 'TIMESTREAM_INFLUXDBCLUSTER_DESIGN_DUPLICATE',
                                      'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-timestream-influxdbcluster.html',
                                                      'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Timestream::InfluxDBInstance': {'paths': ['Name'],
                                       'parent': None,
                                       'mode': 'string',
                                       'type': 'AWS::Timestream::InfluxDBInstance',
                                       'question_index': 1,
                                       'candidate_index': 90,
                                       'rule_id': 'TIMESTREAM_INFLUXDBINSTANCE_DESIGN_DUPLICATE',
                                       'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-timestream-influxdbinstance.html',
                                                       'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::VpcLattice::ServiceNetwork': {'paths': ['Name'],
                                     'parent': None,
                                     'mode': 'string',
                                     'type': 'AWS::VpcLattice::ServiceNetwork',
                                     'question_index': 1,
                                     'candidate_index': 91,
                                     'rule_id': 'VPCLATTICE_SERVICENETWORK_DESIGN_DUPLICATE',
                                     'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-vpclattice-servicenetwork.html',
                                                     'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::XRay::Group': {'paths': ['GroupName'],
                      'parent': None,
                      'mode': 'string',
                      'type': 'AWS::XRay::Group',
                      'question_index': 0,
                      'candidate_index': 94,
                      'rule_id': 'XRAY_GROUP_DESIGN_DUPLICATE',
                      'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-xray-group.html',
                                      'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::XRay::ResourcePolicy': {'paths': ['PolicyName'],
                               'parent': None,
                               'mode': 'string',
                               'type': 'AWS::XRay::ResourcePolicy',
                               'question_index': 0,
                               'candidate_index': 95,
                               'rule_id': 'XRAY_RESOURCEPOLICY_DESIGN_DUPLICATE',
                               'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-xray-resourcepolicy.html',
                                               'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::GatewayRateLimit': {'paths': ['DimensionKeys'],
                                             'parent': ['GatewayIdentifier', 'AWS::BedrockAgentCore::Gateway'],
                                             'mode': 'ordered_array',
                                             'type': 'AWS::BedrockAgentCore::GatewayRateLimit',
                                             'question_index': 1,
                                             'candidate_index': 9,
                                             'rule_id': 'BEDROCKAGENTCORE_GATEWAYRATELIMIT_DESIGN_DUPLICATE',
                                             'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-gatewayratelimit.html',
                                                             'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Cases::Template': {'paths': ['Name'],
                          'parent': ['DomainId', 'AWS::Cases::Domain'],
                          'mode': 'string',
                          'type': 'AWS::Cases::Template',
                          'question_index': 1,
                          'candidate_index': 17,
                          'rule_id': 'CASES_TEMPLATE_DESIGN_DUPLICATE',
                          'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cases-template.html',
                                          'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Cognito::UserPoolGroup': {'paths': ['GroupName'],
                                 'parent': ['UserPoolId', 'AWS::Cognito::UserPool'],
                                 'mode': 'string',
                                 'type': 'AWS::Cognito::UserPoolGroup',
                                 'question_index': 0,
                                 'candidate_index': 29,
                                 'rule_id': 'COGNITO_USERPOOLGROUP_DESIGN_DUPLICATE',
                                 'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cognito-userpoolgroup.html',
                                                 'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Inspector::AssessmentTemplate': {'paths': ['AssessmentTemplateName'],
                                        'parent': ['AssessmentTargetArn', 'AWS::Inspector::AssessmentTarget'],
                                        'mode': 'string',
                                        'type': 'AWS::Inspector::AssessmentTemplate',
                                        'question_index': 0,
                                        'candidate_index': 46,
                                        'rule_id': 'INSPECTOR_ASSESSMENTTEMPLATE_DESIGN_DUPLICATE',
                                        'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-inspector-assessmenttemplate.html',
                                                        'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaConnect::BridgeOutput': {'paths': ['Name'],
                                     'parent': ['BridgeArn', 'AWS::MediaConnect::Bridge'],
                                     'mode': 'string',
                                     'type': 'AWS::MediaConnect::BridgeOutput',
                                     'question_index': 0,
                                     'candidate_index': 53,
                                     'rule_id': 'MEDIACONNECT_BRIDGEOUTPUT_DESIGN_DUPLICATE',
                                     'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-mediaconnect-bridgeoutput.html',
                                                     'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaConnect::BridgeSource': {'paths': ['Name'],
                                     'parent': ['BridgeArn', 'AWS::MediaConnect::Bridge'],
                                     'mode': 'string',
                                     'type': 'AWS::MediaConnect::BridgeSource',
                                     'question_index': 0,
                                     'candidate_index': 54,
                                     'rule_id': 'MEDIACONNECT_BRIDGESOURCE_DESIGN_DUPLICATE',
                                     'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-mediaconnect-bridgesource.html',
                                                     'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaConnect::FlowEntitlement': {'paths': ['Name'],
                                        'parent': ['FlowArn', 'AWS::MediaConnect::Flow'],
                                        'mode': 'string',
                                        'type': 'AWS::MediaConnect::FlowEntitlement',
                                        'question_index': 1,
                                        'candidate_index': 55,
                                        'rule_id': 'MEDIACONNECT_FLOWENTITLEMENT_DESIGN_DUPLICATE',
                                        'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-mediaconnect-flowentitlement.html',
                                                        'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaConnect::FlowOutput': {'paths': ['Name'],
                                   'parent': ['FlowArn', 'AWS::MediaConnect::Flow'],
                                   'mode': 'string',
                                   'type': 'AWS::MediaConnect::FlowOutput',
                                   'question_index': 1,
                                   'candidate_index': 56,
                                   'rule_id': 'MEDIACONNECT_FLOWOUTPUT_DESIGN_DUPLICATE',
                                   'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-mediaconnect-flowoutput.html',
                                                   'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::MediaConnect::FlowVpcInterface': {'paths': ['Name'],
                                         'parent': ['FlowArn', 'AWS::MediaConnect::Flow'],
                                         'mode': 'string',
                                         'type': 'AWS::MediaConnect::FlowVpcInterface',
                                         'question_index': 0,
                                         'candidate_index': 57,
                                         'rule_id': 'MEDIACONNECT_FLOWVPCINTERFACE_DESIGN_DUPLICATE',
                                         'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-mediaconnect-flowvpcinterface.html',
                                                         'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Route53Resolver::FirewallRuleGroupAssociation': {'paths': ['Priority'],
                                                        'parent': ['VpcId', 'AWS::EC2::VPC'],
                                                        'mode': 'integer',
                                                        'type': 'AWS::Route53Resolver::FirewallRuleGroupAssociation',
                                                        'question_index': 0,
                                                        'candidate_index': 72,
                                                        'rule_id': 'ROUTE53RESOLVER_FIREWALLRULEGROUPASSOCIATION_DESIGN_DUPLICATE',
                                                        'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-route53resolver-firewallrulegroupassociation.html',
                                                                        'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ServiceDiscovery::Instance': {'paths': ['InstanceId'],
                                     'parent': ['ServiceId', 'AWS::ServiceDiscovery::Service'],
                                     'mode': 'string',
                                     'type': 'AWS::ServiceDiscovery::Instance',
                                     'question_index': 2,
                                     'candidate_index': 86,
                                     'rule_id': 'SERVICEDISCOVERY_INSTANCE_DESIGN_DUPLICATE',
                                     'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-servicediscovery-instance.html',
                                                     'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Wisdom::MessageTemplate': {'paths': ['Name'],
                                  'parent': ['KnowledgeBaseArn', 'AWS::Wisdom::KnowledgeBase'],
                                  'mode': 'string',
                                  'type': 'AWS::Wisdom::MessageTemplate',
                                  'question_index': 0,
                                  'candidate_index': 92,
                                  'rule_id': 'WISDOM_MESSAGETEMPLATE_DESIGN_DUPLICATE',
                                  'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-wisdom-messagetemplate.html',
                                                  'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::Comprehend::DocumentClassifier': {'paths': ['DocumentClassifierName', 'VersionName'],
                                         'parent': None,
                                         'mode': 'string',
                                         'type': 'AWS::Comprehend::DocumentClassifier',
                                         'question_index': 1,
                                         'candidate_index': 30,
                                         'rule_id': 'COMPREHEND_DOCUMENTCLASSIFIER_DESIGN_DUPLICATE',
                                         'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-comprehend-documentclassifier.html',
                                                         'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::ImageBuilder::ImageRecipe': {'paths': ['Name', 'Version'],
                                    'parent': None,
                                    'mode': 'string',
                                    'type': 'AWS::ImageBuilder::ImageRecipe',
                                    'question_index': 0,
                                    'candidate_index': 42,
                                    'rule_id': 'IMAGEBUILDER_IMAGERECIPE_DESIGN_DUPLICATE',
                                    'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-imagebuilder-imagerecipe.html',
                                                    'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::FSx::DataRepositoryAssociation': {'paths': ['FileSystemPath'],
                                         'parent': ['FileSystemId', 'AWS::FSx::FileSystem'],
                                         'mode': 'string',
                                         'type': 'AWS::FSx::DataRepositoryAssociation',
                                         'question_index': 1,
                                         'candidate_index': 35,
                                         'rule_id': 'FSX_DATAREPOSITORYASSOCIATION_DESIGN_DUPLICATE',
                                         'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-fsx-datarepositoryassociation.html',
                                                         'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::AgentRegistry::RegistryRecord': {'paths': ['Name'],
                                        'parent': ['RegistryId', 'AWS::AgentRegistry::Registry'],
                                        'mode': 'string',
                                        'type': 'AWS::AgentRegistry::RegistryRecord',
                                        'question_index': 2,
                                        'candidate_index': 1,
                                        'rule_id': 'AGENTREGISTRY_REGISTRYRECORD_DESIGN_DUPLICATE',
                                        'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-agentregistry-registryrecord.html',
                                                        'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']},
 'AWS::BedrockAgentCore::Policy': {'paths': ['Name'],
                                   'parent': ['PolicyEngineId', 'AWS::BedrockAgentCore::PolicyEngine'],
                                   'mode': 'string',
                                   'type': 'AWS::BedrockAgentCore::Policy',
                                   'question_index': 0,
                                   'candidate_index': 12,
                                   'rule_id': 'BEDROCKAGENTCORE_POLICY_DESIGN_DUPLICATE',
                                   'source_urls': ['https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-bedrockagentcore-policy.html',
                                                   'https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip']}}
SOURCES = {s["rule_id"]:s["source_urls"] for s in SPECS.values()}


@resource_check(*SPECS)
def evaluate_multi_service_duplicate_names(design,resource):
    spec=SPECS.get(resource.type)
    if spec is None:return []
    ctx=_Context(design,resource);own=owner(ctx,resource,spec);name=token(ctx,resource,spec);duplicate=False
    if own is not None and name is not None:
        for other in design.resources:
            if other.id==resource.id or other.type!=resource.type or other.scope!=resource.scope:continue
            if owner(ctx,other,spec)==own and token(ctx,other,spec)==name:duplicate=True
    return [ctx.finding(spec['rule_id'],'/properties/'+spec['paths'][0],
        'FAIL' if duplicate else 'NEEDS_REVIEW',
        'proves only explicit duplicate keys among distinct same-type resources in the same known design scope and, where required, the same unconditionally linked parent; exact composite keys or documented ASCII case folding only; no duplicate found does not certify uniqueness outside the design; omitted names, conditional references, other scopes, normalization and other clauses of the ledger question remain unverified')]
